{
  # parallelism settings
  "pipe-parallel-size": 0,
  "model-parallel-size": 1,

  # model settings
  "num-layers": 6,
  "hidden-size": 512,
  "num-attention-heads": 8,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "pos-emb": "rotary",
  "rotary-pct": 0.25,
  "no-weight-tying": true,
  "gpt-j-residual": false,
  "output-layer-parallelism": "column",
  
  # "attention-config": [[["flash"], 6]],

  "scaled-upper-triang-masked-softmax-fusion": true,
  # "scaled-upper-triang-masked-softmax-fusion": false,
  "bias-gelu-fusion": false,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.003,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 3.0e-5, #0.0001,
  
  "zero_optimization": {
    # "stage": 1,
    "stage": 0,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  # batch size (trained on 32 gpus)
  "train_micro_batch_size_per_gpu": 16,
  "gradient_accumulation_steps": 2,
  "data-impl": "mmap",
  "num_workers": 1,

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    # "loss_scale": 32768,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "train-iters": 106418, #143000,
  # "lr-decay-iters": 143000,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 2500,
  "eval-interval": 2500,
  "eval-iters": 100,

  "log-interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  "train-data-paths": ["/cache/pile/pile_0.87_deduped_text_document"],
  "valid-data-paths": ["/cache/pile/pile_0.87_deduped_text_document"],
  "test-data-paths": ["/cache/pile/pile_0.87_deduped_text_document"],

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "./pythia-70m-deduped-tokenizer.json",
  "save": "/cache/save_tiny/ckpt",
  "tensorboard_dir": "/cache/save_tiny/tensorboard",
  "load": "/cache/save_tiny/ckpt",
  
  "norm": "rmsnorm",
  "attn_memory_config": {
    "fc_qkv": false, # use nn.Linear for qkv projection if set to true, thus the args of this dict become useless, 
    "value_size": 512,
    "remove_projection": true,
    "shared_projection": false, # use a shared linear for hashing in qkv's tables
    "del_dense": true,
    "dense_size": 512,
    "ffn_num_table": 64,
    "code_length": 8,
    "projection_type": "dense",
    "block_size": 64,
    "learn_weight": false,
    "act_fn": "silu",
  },
  "zero_pad_residual": true,
  "repeat_residual": false,
  "mlp_type": "MemoryBlock",
  "double_mlp_table": true,
  "mlp_expand_type": "extra_bit",
  "memory_config": {
    "remove_projection": true,
    "hidden_size": 512,
    "output_size": 512,
    "ffn_num_table": 64,
    "code_length": 8,
    "projection_type": "dense",
    "block_size": 64,
    "learn_weight": false,
    "act_fn": "silu",
    "act_pos": "none",
  },
  "aux_loss": false,
}
